= Samples
:page-aliases: java:samples.adoc
include::ROOT:partial$include.adoc[]

include::ROOT:partial$new-to-akka-start-here.adoc[]

Samples are available that demonstrate important patterns and abstractions. These can be cloned from their respective repositories. Please refer to the `README` file in each repository for setup and usage instructions.

AI agent that performs a RAG workflow::

Illustrates how to create embeddings for vector databases, how to consume LLMs and maintain conversation history, use RAG to add knowledge to fixed LLMs, and expose it all as a streaming service. It uses MongoDB Atlas and OpenAI.
+
xref:getting-started:ask-akka-agent/index.adoc[Step-by-step guide]
+
link:https://github.com/akka-samples/ask-akka-agent[Github Repository],
Level: Intermediate


AI agent that creates personalized travel itineraries::

Illustrates reliable interaction with an LLM using a workflow. Entities are used for durable state of user preferences and generated trips.
+
link:https://github.com/akka-samples/travel-agent[Github Repository],
Level: Beginner

AI agent that leverages an LLM to process medical discharge summaries::

It assigns tags to the summaries, while also enabling human verification and comparative analysis. Interactions from a workflow with an agent using OpenAI LLM.
+
link:https://github.com/akka-samples/medical-tagging-agent[Github Repository], Level: Intermediate


AI agent that creates release notes summaries::

Every time there is a release from set up GitHub repositories. Interactions with Anthropic Claude from an agent and using tools to retrieve detailed information from GitHub. Entities are used for storing release summaries. Timed action looks for new releases periodically and creates the summary using the LLM.
+
link:https://github.com/akka-samples/changelog-agent[Github Repository], Level: Intermediate

Agentic workflow for customer service::

The real-estate customer service agent is demonstrating how to combine Akka features with an LLM model. It illustrates an agentic workflow for customer service. It processes incoming real-estate inquiries, analyzes the content to extract details, provides follow-up when needed and saves the collected information for future reference.
+
link:https://github.com/akka-samples/real-estate-cs-agent[Github Repository], Level: Intermediate

Trip booking agent using tools::
This app represents an agency that searches for flights and accommodations. It's composed by an LLM (Anthropic) using Spring AI and tools to find flights, accommodations and sending mails.
+
link:https://github.com/akka-samples/trip-agent[Github Repository], Level: Intermediate

Multi-agent, weather-aware travel agent and activity planner::
Demonstrating how to build a multi-agent system using Akka and an LLM model. A workflow manages the user query process, handling the sequential steps of agent selection, plan creation, execution, and summarization.
+
link:https://github.com/akka-samples/multi-agent[Github Repository], Level: Advanced

Analyze sensor data by an agent::
AI agent that uses an LLM to analyze data from fitness trackers, medical records and other sensors. Integration with Fitbit and MongoDB Atlas.
+
link:https://github.com/akka-samples/healthcare-agent[Github Repository], Level: Intermediate

Shopping cart microservice::

Shows a very simple microservice implementing a shopping cart with an event-sourced entity.
+
xref:getting-started:build-and-deploy-shopping-cart.adoc[Step-by-step guide]
+
link:https://github.com/akka-samples/shopping-cart-quickstart[Github Repository], Level: Beginner


A customer registry microservice::

Shows Entities and query capabilities with a View.
link:../java/_attachments/customer-registry-quickstart.zip[customer-registry-quickstart.zip], Level: Intermediate


Involve multiple Entities in a transaction through a Workflow::

A funds transfer workflow between two wallets.
+
link:https://github.com/akka-samples/transfer-workflow-compensation[Github Repository], Level: Intermediate


A choreography saga for user registration::
A user registration service implemented as a Choreography Saga.
+
link:https://github.com/akka-samples/choreography-saga-quickstart[Github Repository], Level: Advanced


Akka Chess::

a complete, resilient, automatically scalable, event-sourced chess game
+
link:https://github.com/akka-samples/akka-chess[Github Repository], Level: Advanced


[sidebar]
It is also possible to deploy a pre-built sample project in https://console.akka.io[the Akka console, window="new"], eliminating the need for local development.

== Maven archetype

To create the build structure of a new service you can use the Maven archetype. From a command window, in the parent directory of the new service, run the following:

[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.akka \
  -DarchetypeArtifactId=akka-javasdk-archetype \
  -DarchetypeVersion={akka-javasdk-version}
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=io.akka ^
  -DarchetypeArtifactId=akka-javasdk-archetype ^
  -DarchetypeVersion={akka-javasdk-version}
----
--

The xref:getting-started:author-your-first-service.adoc[] starts from the Maven archetype and lets you implement a very simple agentic service.
