= Getting started

include::ROOT:partial$include.adoc[]

You might be excited to start your journey learning and building with Akka, but there are a few things you need to get set up first. This will only take a minute.

== Prerequisites

include::ROOT:partial$local-dev-prerequisites.adoc[]
* https://doc.akka.io/operations/cli/installation.html[Akka CLI]
* Git
* AI provider API keys (for AI samples)
* https://account.akka.io/token[Development token for Maven artifact downloads]

== Generating a secure repository token

When you go to the https://account.akka.io/token[repository token] page, you will be presented with two options:

* **Register** - create a new support account.
* **Current customer** - select this if you have already created a support account.

Remember that this account is an _Akka **support** account_ and is not the same thing as an Akka cloud account. This account is specifically for interacting with support and downloading Akka dependency binaries from the secure Maven repository.

Once registered and authenticated, you will see that a secure token has been generated for you.

== Creating an empty project

Before you start exploring all of the samples, you're going to want to make sure that your environment and your local tool chain all work properly. 

First, create a new, _empty_ project by typing `akka code init` in a terminal window and selecting the empty project template. If this is the first time you've run `akka code init`, then it will ask you to go through authenticating against your _support account_ in a browser. You will then choose whether you want the token for the private repository to be in your Maven `settings.xml` file or if you want to add it manually to the pom. 

For the purposes of this test to make sure everything is working, you can put the repository URL in `settings.xml`.

Next, `cd` into the directory that was just created and type `mvn compile`. If this compiles properly, then you're all set! If you did not configure the secure repository token properly, then you may get a compile error with authorization failure/access denied messages. 

If you were able to create and build an empty project, then you can continue on to the rest of the samples.
