= Dynamic orchestration

include::ROOT:partial$include.adoc[]

include::ROOT:partial$new-to-akka-start-here.adoc[]

== Overview

We have used a workflow with predefined steps to call the `WeatherAgent` followed by the `ActivityAgent`. In a larger system there can be many agents, and it would be cumbersome to define a single workflow that would handle all types of requests. A more flexible approach is to let the AI model come up with a plan of which agents to use and in which order to achieve the goal of the request.

In this part of the guide you will:

* Add agents to create a dynamic plan
* Use a workflow that executes the plan

== Prerequisites

include::ROOT:partial$local-dev-prerequisites.adoc[]
* https://platform.openai.com/api-keys[OpenAI API key, window="new"]

== Planner agents

We split the planning into two steps and use two separate agents for these tasks. It's not always necessary to use several steps for the planning. You have to experiment with what works best for your problem domain.

. Select agents that are useful for a certain problem.
. Decide in which order to use the agents and give each agent precise instructions for its task.

The `SelectorAgent` decides which agents to use. Add a new file `SelectorAgent.java` to `src/main/java/com/example/application/`

[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/SelectorAgent.java[SelectorAgent.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/SelectorAgent.java[tag=all]
----
<1> The `AgentRegistry` contains information about all agents.
<2> Select the agents with the role `"worker"`.
<3> Detailed instructions and include descriptions (as json) of the agents.

The result from the `SelectorAgent` is a list of agent ids. Add a new file `AgentSelection.java` to `src/main/java/com/example/domain/`
[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/domain/AgentSelection.java[AgentSelection.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/domain/AgentSelection.java[tag=all]
----

The information about the agents in the `AgentRegistry` comes from the `@Component` and `@AgentDescription` annotations. When using it for planning like this it is important that the agents define those descriptions that the LLM can use to come up with a good plan.

Add the `@AgentDescription` to the `WeatherAgent`:
[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/WeatherAgent.java[WeatherAgent.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/WeatherAgent.java[tag=description]
----

Add the `@AgentDescription` to the `ActivityAgent`:
[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/ActivityAgent.java[ActivityAgent.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/ActivityAgent.java[tag=description]
----

Note that in image:concepts:steps-2.svg[width=20] of the `SelectorAgent` we retrieve a subset of the agents with a certain role. This role is also defined in the `@AgentDescription` annotation.

After selecting agents, we use a `PlannerAgent` to decide in which order to use the agents and the precise request each agent should receive to perform its single task. Add a new file `PlannerAgent.java` to `src/main/java/com/example/application/`

[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/PlannerAgent.java[PlannerAgent.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/PlannerAgent.java[tag=all]
----
<1> Lookup the agent information for the selected agents from the `AgentRegistry.
<2> Detailed instructions and include descriptions (as json) of the agents.

The result from the `PlannerAgent` is a `Plan` with a list of `PlanStep`.

Add a new file `Plan.java` to `src/main/java/com/example/domain/`
[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/domain/Plan.java[Plan.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/domain/Plan.java[tag=all]
----

and a new file `PlanStep.java` to `src/main/java/com/example/domain/`
[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/domain/PlanStep.java[PlanStep.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/domain/PlanStep.java[tag=all]
----

== Common signature of worker agents

We will call the selected agents according to the plan, and we want to do that without explicitly knowing which agent it is. For this, the worker agents (`WeatherAgent` and `ActivityAgent`) must have the same shape. Adjust the `ActivityAgent` to have this method signature:

[source,java,indent=0]
.ActivityAgent.java
----
  public Effect<String> query(AgentRequest request) {
----

Where `AgentRequest` is a new record. Add a new file `AgentRequest.java` to `src/main/java/com/example/domain/`

[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/domain/AgentRequest.java[AgentRequest.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/domain/AgentRequest.java[tag=all]
----

Remove the previous `ActivityAgent.Request`, and update all references to use the new `AgentRequest` instead.

Make the same changes to the `WeatherAgent`. Use the same method signature and use the `AgentRequest` record.

== Execute the plan

`SelectorAgent` and `PlannerAgent` are the two agents that perform the planning, but we also need to connect them and execute the plan. This orchestration is the job of the workflow.

Update the `AgentTeamWorkflow` to this:

[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/AgentTeamWorkflow.java[AgentTeamWorkflow.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/AgentTeamWorkflow.java[tag=all]
----
<1> It's a workflow, with reliable and durable execution.
<2> The steps are select - plan - execute - summarize.
<3> The workflow starts by selecting agents
<4> which is performed by the `SelectorAgent`.
<5> Continue with making the actual plan
<6> which is performed by the `PlannerAgent`, using the selection from the previous step.
<7> Continue with executing the plan.
<8> Take the next task in the plan.
<9> Call the agent for the task.
<10> Continue executing the plan until no tasks are remaining.

You can add the imports:
[source,java,indent=0]
----
import static com.example.application.AgentTeamWorkflow.Status.*;
import com.example.domain.*;
----

When executing the plan and calling the agents we know the id of the agent to call, but not the agent class. It can be the `WeatherAgent` or `ActivityAgent`. Therefore, we can't use the ordinary `method` of the `ComponentClient. Instead, we use the `dynamicCall` with the id of the agent. This is the reason why we had to align the method signatures of the worker agents.

This also ends the workflow by creating a summary of the results from the involved agent. Add a new file `SummarizerAgent.java` to `src/main/java/com/example/application/`

[source,java,indent=0]
.{sample-base-url}/multi-agent/src/main/java/demo/multiagent/application/SummarizerAgent.java[SummarizerAgent.java]
----
include::java:example$multi-agent/src/main/java/demo/multiagent/application/SummarizerAgent.java[tag=all]
----

Fix any compilation errors, such as missing imports.

[source,command line]
----
mvn compile
----

We still only have the two worker agents `WeatherAgent` and `ActivityAgent`, but you can add more agents to this structure of dynamic planning and execution, and it will be able to solve other types of problems without changing the orchestration engine.

== Running the service

Start your service locally:

[source,command line]
----
mvn compile exec:java
----

Ask for activities:

[source, command line]
----
curl -i -XPOST --location "http://localhost:9000/activities/alice" \
  --header "Content-Type: application/json" \
  --data '{"message": "I am in Madrid. What should I do? Beware of the weather."}'
----

Retrieve the suggested activities with the `sessionId` from the previous response:

[source, command line]
----
curl -i -XGET --location "http://localhost:9000/activities/alice/{sessionId}"
----

Inspect the logs and notice the difference if you include "Beware of the weather" in the request or not.

== Next steps

* Finally, let's use another agent to evaluate the previous suggestions when the user preferences are changed or if new suggestions should be created. Continue with xref:planner-agent/eval.adoc[] that will illustrate the Consumer component and "LLM as judge" pattern.

