= Install the Akka CLI
:page-aliases: reference:cli/installation.adoc

include::ROOT:partial$include.adoc[]

The Akka CLI, `akka` enables you to interact with Akka projects. To install it, follow these steps:

[.tabset]
Linux::
+
--
**Recommended approach**

The recommended approach to install the `akka` CLI on Linux is using the Debian package repository:

[source,bash,subs="attributes"]
----
curl -1sLf \
  'https://dl.cloudsmith.io/public/lightbend/public-akka/setup.deb.sh' \
  | sudo -E bash
sudo apt install akka
----

If the `akka` CLI is already installed, and you want to upgrade to the latest version, you can run:

[source,bash]
----
sudo apt update
sudo apt install --only-upgrade akka
----

**Alternative approach**

[source,bash]
....
curl -sL https://doc.akka.io/install-cli.sh | bash
....

If that fails due to permission issues, use:

[source,bash]
....
curl -sL https://doc.akka.io/install-cli.sh | bash -s -- --prefix /tmp && \
    sudo mv /tmp/akka /usr/local/bin/akka
....

You can pass options to the installer script with `-s --` e.g.:

[source,bash,subs="attributes"]
....
curl -sL https://doc.akka.io/install-cli.sh | bash -s -- --prefix=$HOME --version={akka-cli-version} --verbose
curl -sL https://doc.akka.io/install-cli.sh | bash -s -- -P $HOME -v {akka-cli-version} -V
....

--
macOS::
+
--
**Recommended approach**

The recommended approach to install `akka` on macOS, is using https://brew.sh[brew, window="new"]

[source,bash]
----
brew install akka/brew/akka
----

If the `akka` CLI is already installed, and you want to upgrade `akka` to the latest version, you can run

[source,bash]
----
brew update
brew upgrade akka
----

**Alternative approach**

....
curl -sL https://doc.akka.io/install-cli.sh | bash
....

You can pass options to the installer script with `-s --` e.g.:

[source,bash,subs="attributes"]
....
curl -sL https://doc.akka.io/install-cli.sh | bash -s -- --prefix=$HOME --version={akka-cli-version} --verbose
curl -sL https://doc.akka.io/install-cli.sh | bash -s -- -P $HOME -v {akka-cli-version} -V
....
--
Windows::
+
--
**Recommended approach**

The recommended approach to install the `akka` CLI on Windows is using https://learn.microsoft.com/en-us/windows/package-manager/winget/[winget]:

[source,powershell]
----
winget install Akka.AkkaCli
----

If the `akka` CLI is already installed, and you want to upgrade to the latest version, you can run:

[source,powershell]
----
winget upgrade Akka.AkkaCli
----

**Alternative approach**

. Download the latest version of `akka` from https://downloads.akka.io/latest/akka_windows_amd64.zip[https://downloads.akka.io/latest/akka_windows_amd64.zip]

. Optionally, you can verify the integrity of the downloaded files using the https://downloads.akka.io/latest/checksums.txt[SHA256 checksums].

. Extract the zip file and move `akka.exe` to a location on your `%PATH%`.

--

NOTE: By downloading and using this software you agree to Akka's https://akka.io/legal/privacy[Privacy Policy] and https://trust.akka.io/cloud-terms-of-service[Software Terms of Use].

Verify that the Akka CLI has been installed successfully by running the following to list all available commands:

[source, command window]
----
akka help
----

== Related documentation

- xref:cli/using-cli.adoc[]
- xref:cli/command-completion.adoc[]
- xref:reference:cli/akka-cli/index.adoc[]
