apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service-svc
  namespace: shopping-cart-namespace
spec:
  selector:
    app: shopping-cart-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
