= akka

Akka control

== Synopsis

Welcome to the Akka CLI, for more information on its usage please visit the documentation https://doc.akka.io/index.html.

== Options

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -h, --help                help for akka
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:cli/akka_auth[akka auth]	 - Manage Akka authentication.
* link:cli/akka_completion[akka completion]	 - Generate shell completion scripts
* link:cli/akka_config[akka config]	 - Manage configuration and context for the Akka CLI.
* link:cli/akka_container-registry[akka container-registry]	 - Manage and push service images to the Akka Container Registry.
* link:cli/akka_docker[akka docker]	 - Manage credentials for projects using private Docker registries.
* link:cli/akka_docs[akka docs]	 - Open the Akka documentation page
* link:cli/akka_local[akka local]	 - Interact with and manage Akka services running locally.
* link:cli/akka_logs[akka logs]	 - Display the last few lines of logs for a specific service.
* link:cli/akka_organizations[akka organizations]	 - Manage your organizations on Akka
* link:cli/akka_projects[akka projects]	 - Manage your Akka projects.
* link:cli/akka_quickstart[akka quickstart]	 - Akka quickstart project samples.
* link:cli/akka_regions[akka regions]	 - Manage available regions.
* link:cli/akka_roles[akka roles]	 - Manage the user roles for an Akka project.
* link:cli/akka_routes[akka routes]	 - Manage routes for your Akka project.
* link:cli/akka_secrets[akka secrets]	 - Manage secrets for an Akka project.
* link:cli/akka_services[akka services]	 - Manage and deploy services on Akka.
* link:cli/akka_version[akka version]	 - Print the akka CLI version

[discrete]

