= akka projects

Manage your Akka projects.

== Synopsis

The `akka projects` commands manipulate the projects in your Akka account, where a project is a collection of services.
A project can be deployed to one or more regions.
For more details on projects, see https://doc.akka.io/operations/projects/index.html

== Options

----
  -h, --help   help for projects
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,go-template=] (default "text")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:cli/akka[akka]	 - Akka control
* link:cli/akka_projects_config[akka projects config]	 - Manage project configs.
* link:cli/akka_projects_delete[akka projects delete]	 - Delete a project.
* link:cli/akka_projects_get[akka projects get]	 - Get project information.
* link:cli/akka_projects_hostnames[akka projects hostnames]	 - Manage hostnames for your Akka project.
* link:cli/akka_projects_list[akka projects list]	 - List all projects.
* link:cli/akka_projects_new[akka projects new]	 - Create a new Akka project.
* link:cli/akka_projects_observability[akka projects observability]	 - Manage the observability settings for your Akka project.
* link:cli/akka_projects_open[akka projects open]	 - Open the current project in the console.
* link:cli/akka_projects_regions[akka projects regions]	 - Manage the regions assigned to your Akka project.
* link:cli/akka_projects_tokens[akka projects tokens]	 - Manage your Akka project service tokens.
* link:cli/akka_projects_update[akka projects update]	 - Update project attributes such as name and description.

[discrete]

