= Adding a view to the shopping cart

include::ROOT:partial$include.adoc[]

This guide walks you through the design and implementation of a shopping cart service, illustrating the use of some of Akka's components.

== Overview

In this step in the shopping cart sample tour, we'll be taking a look at the event and domain models created in the previous step. We'll decide on what we'd like to change and then implement that change in the form of a few refactorings and adding a new `View`.

== Prerequisites

include::ROOT:partial$cloud-dev-prerequisites.adoc[]

== Clone the sample

. Clone the full source code of the Shopping Cart sample from link:https://github.com/akka-samples/shopping-cart-addview[Github].

== Re-evaluating the shopping cart structure

The first version of the shopping cart has a bit of an issue blurring the lines between tiers or responsibilities. The data type used to represent the `LineItem` in the `POST` request to the HTTP endpoint is the same data type sent to the `ShoppingCartEntity` as a command. This is _also_ the exact same data type used by the entity for its own internal state storage.

For small applications or prototypes, this isn't that big of a problem. But we can see this kind of pattern will create headaches in the future. Any change to the way the entity internally stores its state will potentially break the API endpoint and maybe even cause migration issues with events.

It might seem like overkill at first, but it's one of the first steps toward supporting evolutionary architecture and clean, easily-maintained code. If we adopt the rule that we can't reuse the same data type across roles, then we end up with 3 distinct data types:

* The data used to shape the body of the `POST` request to add an item to a cart
* The data used as a _command_ to be sent to the entity to handle that request
* The data used _internally_ by the entity to represent its own state.

Aside from the obvious desire to untangle spaghetti, we also want to make sure that the data the entity is storing as its state contains _only_ the information the entity needs in order to validate incoming commands.

== Creating isolated data types

TBD

== Adding a shopping cart view

TBD


