akka.javasdk {
  agent {
    model-provider = openai

    openai {
      model-name = "gpt-4.1"
      api-key = ${?OPENAI_API_KEY}
    }

    googleai-gemini {
      model-name = "gemini-3-flash-preview"
      api-key = ${?GOOGLE_AI_GEMINI_API_KEY}
    }

    anthropic {
      model-name = "claude-haiku-4-5"
      api-key = ${?ANTHROPIC_API_KEY}
    }
  }
}
