name: Documentation to doc.akka.io
on:
  workflow_dispatch:
  push:
    branches:
      - 'docs-current'

permissions:
  contents: read

jobs:
  build:
    name: scp to Gustav
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: docs-current
          fetch-tags: true # required for version.sh
          # we don't know what commit the last tag was, it's safer to get entire repo
          fetch-depth: 0

      - name: Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.21

      - name: Downloads, Antora
        run: |
          make managed prod

      - name: LLM friendly markdown
        run: |
          sudo ./docs/bin/docs2markdown.sh

      - name: rsync
        run: |
          ./docs/bin/rsync-docs.sh "target/site/*" akkarepo@gustav.akka.io:www/
        env:
          SCP_SECRET: ${{ secrets.AKKA_RSYNC_GUSTAV }}

      - name: llm-ctx.txt
        run: |
          sudo chmod a+w target/site
          pip install llms-txt
          sudo cp docs/src/modules/ROOT/pages/llms.txt target/site/
          llms_txt2ctx target/site/llms.txt > target/site/llms-ctx.txt
          llms_txt2ctx target/site/llms.txt --optional true > target/site/llms-ctx-full.txt
          ./docs/bin/rsync-docs.sh "target/site/llms*.txt" akkarepo@gustav.akka.io:www/snapshots/akka-documentation/
        env:
          SCP_SECRET: ${{ secrets.AKKA_RSYNC_GUSTAV }}
