name: Deploy WIP to doc.akka.io/snapshots/
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    name: scp to Gustav
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: main
          fetch-tags: true # required for version.sh

      - name: Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.21

      - name: Downloads, Antora
        run: |
          make managed local

      - name: SCP to Gustav
        run: |
          ./docs/bin/deploy-site.sh akkarepo@gustav.akka.io:www/snapshots/akka-documentation/
        env:
          SCP_SECRET: ${{ secrets.GUSTAV_SCP_SECRET }}
