name: Update CLI docs

on:
  workflow_dispatch:

jobs:
  gen-cli-docs:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      # https://github.com/actions/checkout/releases
      # v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Set up Ruby
      # https://github.com/ruby/setup-ruby/releases
      # v1.177.0
      uses: ruby/setup-ruby@6615b4b8a02c78c4d711c06df4b8a20aa685a45d
      with:
        ruby-version: '3.1'

    - name: Install Akka CLI and create the CLI docs
      id: install-cli
      run: |
        export CLI_INSTALL_PATH=$HOME/.akka/bin
        export PATH=${PATH}:${CLI_INSTALL_PATH}
        mkdir -p ${CLI_INSTALL_PATH}
        chmod +x docs/src-static/install-cli.sh
        docs/src-static/install-cli.sh --force --prefix=${CLI_INSTALL_PATH}
        CLI_VERSION=$(akka version)
        echo "setting CLI version to ${CLI_VERSION}"
        sed -i.bak "s/\(echo \":akka-cli-version: \)[^\"]*/\1${CLI_VERSION}/" Makefile
        rm Makefile.bak
        gem install kramdown-asciidoc
        ./docs/bin/generate_cli_docs.sh gen-index

    - name: Create Pull Request
      # https://github.com/peter-evans/create-pull-request/releases
      # v7.0.5
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
      with:
        title: "docs: akka CLI docs"
        branch-suffix: short-commit-hash
        body: |
          Latest Akka CLI help texts
        delete-branch: true
        labels: cli, documentation
        commit-message: "docs: akka CLI docs"
        author: "GitHub <noreply@github.com>"
