name: Documentation

on:
  workflow_dispatch: # Manually triggered workflow until docs are ready
  pull_request:
    paths:
      - 'docs/**'
      - 'samples/**'

#  push:
#    branches:
#      - main
#    tags-ignore: [ v.* ]

permissions:
  contents: read
  pull-requests: write

jobs:
  make-docs:
    name: "Make docs"
    runs-on: Akka-Default
    steps:
      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts
          fetch-depth: 0

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.21

      - name: Make docs and validate links
        # validate-links not enabled yet, waiting for fixing broken links
        run: make managed local

  vale:
    name: "Vale style checking"
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor

      # https://vale.sh
      - name: Vale
        # https://github.com/errata-ai/vale-action/releases
        uses: errata-ai/vale-action@v2.1.1
        with:
          version: 3.7.1
          files: docs/src
          fail_on_error: true
          filter_mode: nofilter
          vale_flags: "--config=docs/.vale.ini"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  verify-include-paths:
    runs-on: Akka-Default

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Run path verification script
        run:
          ./docs/bin/verify-include-paths.sh
