# https://github.com/marketplace/actions/labeler

name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    permissions:
      contents: read
      pull-requests: write
    steps:
      # https://github.com/actions/labeler/releases
      # v4.0.3
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '../labeler.yml'
