name: Publish sample docker images

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Publish ]
    types:
      - completed

permissions:
  contents: read

jobs:
  validate-tag:
    name: Don't publish pre-releases
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    outputs:
      should-publish: ${{ steps.check.outputs.should-publish }}
      latest-tag: ${{ steps.check.outputs.latest-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Check latest tag pattern
        id: check
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          echo "Latest tag: $LATEST_TAG"
          echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          
          if [[ $LATEST_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Latest tag matches version pattern (no milestone releases), should publish"
            echo "should-publish=true" >> $GITHUB_OUTPUT
          else
            echo "Latest tag does not match version pattern or is a milestone release, skipping publish"
            echo "Expected pattern: v1.0.0, v2.1.3, etc. (no dashes allowed)"
            echo "should-publish=false" >> $GITHUB_OUTPUT
          fi

  publish-sample-images:
    name: Build and publish sample docker images
    runs-on: ubuntu-22.04
    needs: validate-tag
    if: needs.validate-tag.outputs.should-publish == 'true'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Cache M2 dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-repo-

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.21

      - name: Update SDK version
        id: update_sdk_version
        run: |-
          # use latest tag
          docs/bin/version.sh > ~/akka-javasdk-version.txt
          export SDK_VERSION="$(cat ~/akka-javasdk-version.txt)"
          echo "SDK version: '${SDK_VERSION}'"
          ./updateSdkVersions.sh java samples/shopping-cart-quickstart

      - name: Quickstart docker image for console quick-deploy
        run: |-
          cd samples/shopping-cart-quickstart
          echo "${{ secrets.PUBLISH_PASSWORD }}" | docker login --username "${{ secrets.PUBLISH_USER }}" --password-stdin registry.akka.io
          mvn --batch-mode deploy docker:push -DskipTests -Ddocker.image=registry.akka.io/shopping-cart-quickstart
