= akka models

Deploy and serve models in Akka's inference regions.

== Options

----
  -h, --help   help for models
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose             set verbose output
----

== SEE ALSO

* link:akka.html[akka]	 - Akka control
* link:akka_models_allocations.html[akka models allocations]	 - Manage the project's accelerator allocations in a region.
* link:akka_models_apply.html[akka models apply]	 - Apply a model descriptor to the project's region.
* link:akka_models_delete.html[akka models delete]	 - Delete the resources a model descriptor names.
* link:akka_models_endpoints.html[akka models endpoints]	 - Manage the endpoints that serve models through the gateway.
* link:akka_models_get.html[akka models get]	 - Describe one model;
--wait blocks until it is Ready.
* link:akka_models_list.html[akka models list]	 - List the project's models in the region.
* link:akka_models_pools.html[akka models pools]	 - Discover the accelerator pools the organization's regions offer.

[discrete]

