= akka optimize eval datasets

Test cases, versioned at import

== Options

----
  -h, --help   help for datasets
----

== Options inherited from parent commands

----
      --cache-file string    location of cache file (default "~/.akka/cache.yaml")
      --config string        location of config file (default "~/.akka/config.yaml")
      --context string       configuration context to use
      --disable-prompt       Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                             This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
      --force                Skip the confirmation prompt
      --jq string            Filter the JSON output with a jq expression
      --json string          Output JSON with only these fields; --json= lists the fields a command offers
      --no-color             Print without color, as NO_COLOR does
  -o, --output string        set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string     the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet                set quiet output (helpful when used as part of a script)
      --region string        Region to use if the project has more than one region
      --timeout duration     client command timeout (default 10s)
      --trainer-url string   Trainer service URL (default http://localhost:9001, or TRAINER_URL)
      --url string           Optimize service URL (default http://localhost:9010, or OPTIMIZE_URL)
      --use-grpc-web         use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose              set verbose output
----

== SEE ALSO

* link:akka_optimize_eval.html[akka optimize eval]	 - Datasets, experiments and the evaluators that score them
* link:akka_optimize_eval_datasets_create.html[akka optimize eval datasets create]	 - Upload a dataset file and version it
* link:akka_optimize_eval_datasets_get.html[akka optimize eval datasets get]	 - One dataset: what it holds, what scores it, and every version it has had
* link:akka_optimize_eval_datasets_imports.html[akka optimize eval datasets imports]	 - Progress of a dataset import
* link:akka_optimize_eval_datasets_items.html[akka optimize eval datasets items]	 - The items in one version of a dataset
* link:akka_optimize_eval_datasets_list.html[akka optimize eval datasets list]	 - Datasets that have been imported, most recently imported first

[discrete]

