= akka local services components agents instances

Manage autonomous agent instances.

== Synopsis

The `akka local service components agents instances` commands list and operate on individual autonomous agent instances.

== Options

----
  -h, --help   help for instances
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose             set verbose output
----

== SEE ALSO

* link:akka_local_services_components_agents.html[akka local services components agents]	 - Manage autonomous agent components.
* link:akka_local_services_components_agents_instances_describe.html[akka local services components agents instances describe]	 - Describe the current state of an autonomous agent instance.
* link:akka_local_services_components_agents_instances_list.html[akka local services components agents instances list]	 - List active autonomous agent instances for a component within a time range.
* link:akka_local_services_components_agents_instances_resume.html[akka local services components agents instances resume]	 - Resume a suspended autonomous agent instance.
* link:akka_local_services_components_agents_instances_suspend.html[akka local services components agents instances suspend]	 - Suspend an autonomous agent instance.
* link:akka_local_services_components_agents_instances_terminate.html[akka local services components agents instances terminate]	 - Terminate an autonomous agent instance.

[discrete]

