= akka secrets external

Manage external secrets for an Akka project.

== Synopsis

The `akka secrets external` command manages external secrets for the currently configured project.
These secrets can be mounted in a services container.

== Options

----
  -h, --help   help for external
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_secrets.html[akka secrets]	 - Manage secrets for an Akka project.
* link:akka_secrets_external_create.html[akka secrets external create]	 - Create an external secret in the current project.
* link:akka_secrets_external_delete.html[akka secrets external delete]	 - Delete an external secret from the current project.
* link:akka_secrets_external_get.html[akka secrets external get]	 - Get an external secret in the current project.
* link:akka_secrets_external_info.html[akka secrets external info]	 - List information for how to configure external secrets for each Akka project region.
* link:akka_secrets_external_list.html[akka secrets external list]	 - List the external secrets in the current project.
* link:akka_secrets_external_update.html[akka secrets external update]	 - Update an external secret in the current project.

[discrete]

