= akka services jwks

Manage JWT keysets of a service.

== Options

----
  -h, --help   help for jwks
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose             set verbose output
----

== SEE ALSO

* link:akka_services.html[akka services]	 - Manage and deploy services on Akka.
* link:akka_services_jwks_add.html[akka services jwks add]	 - Add a JWT keyset to a service.
* link:akka_services_jwks_generate.html[akka services jwks generate]	 - Generate a JWKS key and add it as a keyset to a service.
* link:akka_services_jwks_list.html[akka services jwks list]	 - List all JWT keysets for a service.
* link:akka_services_jwks_migrate.html[akka services jwks migrate]	 - Migrate JWT keys to JWKS keysets.
* link:akka_services_jwks_remove.html[akka services jwks remove]	 - Remove a JWT keyset from a service.
* link:akka_services_jwks_update.html[akka services jwks update]	 - Update a JWT keyset on a service.

[discrete]

