= akka optimize routing-policies

What serves a use-case, and in what share

== Options

----
  -h, --help   help for routing-policies
----

== Options inherited from parent commands

----
      --cache-file string    location of cache file (default "~/.akka/cache.yaml")
      --config string        location of config file (default "~/.akka/config.yaml")
      --context string       configuration context to use
      --disable-prompt       Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                             This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
      --force                Skip the confirmation prompt
      --jq string            Filter the JSON output with a jq expression
      --json string          Output JSON with only these fields; --json= lists the fields a command offers
      --no-color             Print without color, as NO_COLOR does
  -o, --output string        set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string     the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet                set quiet output (helpful when used as part of a script)
      --region string        Region to use if the project has more than one region
      --timeout duration     client command timeout (default 10s)
      --trainer-url string   Trainer service URL (default http://localhost:9001, or TRAINER_URL)
      --url string           Optimize service URL (default http://localhost:9010, or OPTIMIZE_URL)
      --use-grpc-web         use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose              set verbose output
----

== SEE ALSO

* link:akka_optimize.html[akka optimize]	 - Own your intelligence: cost, models, training and routing
* link:akka_optimize_routing-policies_apply.html[akka optimize routing-policies apply]	 - Publish a policy version
* link:akka_optimize_routing-policies_get.html[akka optimize routing-policies get]	 - The current policy and its history
* link:akka_optimize_routing-policies_rollback.html[akka optimize routing-policies rollback]	 - Republish a previous version
* link:akka_optimize_routing-policies_route.html[akka optimize routing-policies route]	 - Set the shadow and canary dials;
0 removes
* link:akka_optimize_routing-policies_veto.html[akka optimize routing-policies veto]	 - Refuse routing changes until lifted

[discrete]

