= akka services components workflows

Inspect and manage workflow executions.

== Synopsis

The `akka service components workflows` commands let you inspect and manage running workflow executions for a given service and workflow component.

== Options

----
  -h, --help   help for workflows
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose             set verbose output
----

== SEE ALSO

* link:akka_services_components.html[akka services components]	 - Inspect components of a service.
* link:akka_services_components_workflows_delete-snapshot.html[akka services components workflows delete-snapshot]	 - Delete the stored state snapshot of a single workflow instance.
* link:akka_services_components_workflows_force-snapshot.html[akka services components workflows force-snapshot]	 - Create a state snapshot of a single workflow instance now.
* link:akka_services_components_workflows_get.html[akka services components workflows get]	 - Get workflow execution details for the specified service, workflow component id and workflow id
* link:akka_services_components_workflows_get-state.html[akka services components workflows get-state]	 - Get the state for the given service, workflow component and id.
* link:akka_services_components_workflows_list-events.html[akka services components workflows list-events]	 - List events from the event journal for the given service, workflow component and id.
* link:akka_services_components_workflows_list-ids.html[akka services components workflows list-ids]	 - List recently active IDs for the given workflow component served by this service within specified time window (24h by default).
* link:akka_services_components_workflows_resume.html[akka services components workflows resume]	 - Resume a suspended workflow execution.
* link:akka_services_components_workflows_suspend.html[akka services components workflows suspend]	 - Suspend a running workflow execution.
* link:akka_services_components_workflows_terminate.html[akka services components workflows terminate]	 - Terminate a running workflow execution.

[discrete]

