= akka organizations identity-providers

Manage workload identity providers for your organization on Akka

== Synopsis

The `akka organizations identity-providers` commands manage the workload identity providers for organizations in Akka.
Workload identity providers enable third party cloud services to authenticate as Akka principals without needing to synchronise credentials, by validating inbound JWTs issued by a trusted OIDC issuer.

== Options

----
  -h, --help   help for identity-providers
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
      --verbose             set verbose output
----

== SEE ALSO

* link:akka_organizations.html[akka organizations]	 - Manage your organizations on Akka
* link:akka_organizations_identity-providers_add.html[akka organizations identity-providers add]	 - Add a workload identity provider to your organization on Akka
* link:akka_organizations_identity-providers_list.html[akka organizations identity-providers list]	 - List the workload identity providers for the current (or specified) organization
* link:akka_organizations_identity-providers_remove.html[akka organizations identity-providers remove]	 - Remove the given workload identity provider from the current (or specified) organization
* link:akka_organizations_identity-providers_show.html[akka organizations identity-providers show]	 - Display information about the given workload identity provider for the current (or specified) organization
* link:akka_organizations_identity-providers_update.html[akka organizations identity-providers update]	 - Update a workload identity provider for your organization on Akka

[discrete]

