= akka projects observability add logs

Add a logs exporter for your Akka project.

== Synopsis

The `akka project observability add logs` command adds a logs exporter for your Akka project.

== Options

----
  -h, --help   help for logs
----

== Options inherited from parent commands

----
      --cache-file string   location of cache file (default "~/.akka/cache.yaml")
      --config string       location of config file (default "~/.akka/config.yaml")
      --context string      configuration context to use
      --disable-prompt      Disable all interactive prompts when running akka commands. If input is required, defaults will be used, or an error will be raised.
                            This is equivalent to setting the environment variable AKKA_DISABLE_PROMPTS to true.
  -o, --output string       set output format to one of [text,json,json-compact,go-template=] (default "text")
      --page-mode string    the mode for paging, either paged, buffered or auto. (default "auto")
  -q, --quiet               set quiet output (helpful when used as part of a script)
      --timeout duration    client command timeout (default 10s)
      --use-grpc-web        use grpc-web when talking to Akka APIs. This is useful when behind corporate firewalls that decrypt traffic but don't support HTTP/2.
  -v, --verbose             set verbose output
----

== SEE ALSO

* link:akka_projects_observability_add.html[akka projects observability add]	 - Add an exporter to the observability settings for your Akka project.
* link:akka_projects_observability_add_logs_azure-monitor.html[akka projects observability add logs azure-monitor]	 - Add an Azure Monitor exporter for logs.
* link:akka_projects_observability_add_logs_google-cloud.html[akka projects observability add logs google-cloud]	 - Add a Google Cloud exporter for logs.
* link:akka_projects_observability_add_logs_otlp.html[akka projects observability add logs otlp]	 - Add an OTLP gRPC exporter for logs.
* link:akka_projects_observability_add_logs_otlp-http.html[akka projects observability add logs otlp-http]	 - Add an OTLP HTTP exporter for logs.
* link:akka_projects_observability_add_logs_splunk-hec.html[akka projects observability add logs splunk-hec]	 - Add a Splunk HEC exporter for logs.

[discrete]

